default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Grahhs1995family
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_app_development

test:
  <<: *default
  database: Blog_app_test

production:
  <<: *default
  database: Blog_app_production
  